<?php
use ShootCalTestimonials\{Form,Meta,Assets,Shortcode,Config,Editor};
if ( ! defined('WP_CLI') || ! WP_CLI || ! in_array(wp_parse_url(home_url(), PHP_URL_HOST), ['localhost','127.0.0.1','::1','shootcal-plugin-dev.local'], true) ) { throw new RuntimeException('Run only in disposable localhost QA.'); }
function check($v,$m){if(!$v)throw new RuntimeException($m);echo "PASS $m\n";}
$made=[];
try{
 $quote="Literal \\ path, client's apostrophe — line one.\n\nLine two with more than twenty characters.";
 $p=wp_insert_post(wp_slash(['post_type'=>'shootcal_testimonial','post_status'=>'publish','post_title'=>'Regression Example','post_content'=>$quote]));$made[]=$p;
 $second=wp_insert_post(['post_type'=>'shootcal_testimonial','post_status'=>'publish','post_title'=>'Regression Unrated','post_content'=>'Another complete test review.']);$made[]=$second;
 $html=(new Shortcode)->render(['count'=>'60','more'=>'show','total'=>'60']);
 check(substr_count($html,'data-sct-card')<=60,'render ceiling respected');
 check(str_contains((new Shortcode)->render(['count'=>'1','total'=>'1','more'=>'show']),'data-sct-more'),'stale View more total still offers a next review');
 wp_update_post(['ID'=>$second,'post_status'=>'draft']);check(str_contains((new Shortcode)->render(['count'=>'1']),'data-sct-card'),'single review list reaches asset and schema hooks without type error');wp_update_post(['ID'=>$second,'post_status'=>'publish']);
 $a=(new Shortcode)->render(['count'=>'60']);$b=(new Shortcode)->render(['count'=>'60']);preg_match_all('/ id="([^"]+)"/',$a.$b,$ids);check(count($ids[1])===count(array_unique($ids[1])),'dialog IDs unique across separate renderers');
 check(str_contains($a,esc_html($quote)),'literal quote punctuation backslashes and paragraphs preserved');
 $sorted=(new Shortcode)->render(['orderby'=>'rating','count'=>'60']);check(str_contains($sorted,'Regression Unrated'),'rating sort includes unrated reviews');
 $form=new Form;$method=new ReflectionMethod(Form::class,'posted_rating');
 foreach(['-5','3.2','3abc','7'] as $value){$_POST[Form::FIELD_RATING]=$value;check($method->invoke($form)===0,'rejects invalid score '.$value);}
 $_POST[Form::FIELD_RATING]='5';check($method->invoke($form)===5,'accepts valid score');
 $insert=new ReflectionMethod(Form::class,'insert');$new=$insert->invoke($form,'Regression Submitter',$quote,0,'','private@example.test');$made[]=$new;
 check(get_post($new)->post_content===$quote,'public submission stores exact sanitized wording');check(get_post_status($new)==='pending','public submissions remain pending');
 wp_set_current_user(0);$req=new WP_REST_Request('GET','/wp/v2/shootcal_testimonial/'.$p);$res=rest_do_request($req);check($res->get_status()===200,'anonymous REST reads published review');
 update_post_meta($p,'shootcal_testimonials_consent_note','PRIVATE TEST NOTE');update_post_meta($p,'shootcal_testimonials_source_note','PRIVATE RESEARCH');update_post_meta($p,Form::EMAIL_META_KEY,'private@example.test');
 $res=rest_do_request($req);$meta=$res->get_data()['meta']??[];check(!array_intersect_key($meta,array_flip(['shootcal_testimonials_consent_note','shootcal_testimonials_source_note',Form::EMAIL_META_KEY])),'private notes and email absent from anonymous REST');
 $pending=rest_do_request(new WP_REST_Request('GET','/wp/v2/shootcal_testimonial/'.$new));check($pending->get_status()!==200,'anonymous cannot read pending review');
 $admin=get_users(['role'=>'administrator','number'=>1])[0];wp_set_current_user($admin->ID);
 $req=new WP_REST_Request('POST','/wp/v2/shootcal_testimonial/'.$p);$req->set_param('meta',['shootcal_testimonials_rating'=>4,'shootcal_testimonials_source'=>'google','shootcal_testimonials_source_url'=>'https://example.test/review']);$res=rest_do_request($req);check($res->get_status()===200&&get_post_meta($p,'shootcal_testimonials_rating',true)==4,'editor REST updates rating and source');
 $req=new WP_REST_Request('GET','/wp/v2/shootcal_testimonial/'.$p);$req->set_param('context','edit');$res=rest_do_request($req);check(($res->get_data()['meta']['shootcal_testimonials_consent_note']??'')==='PRIVATE TEST NOTE','private annotations available in authorized edit context');
 wp_set_current_user(0);$_GET['shootcal_testimonials_category']=['malformed'];check(is_string((new Shortcode)->render(['allow_query'=>'on'])),'array query parameter does not crash');unset($_GET['shootcal_testimonials_category']);
 $resolve=new ReflectionMethod(Shortcode::class,'resolve_category');check($resolve->invoke(new Shortcode,'preset','on')==='preset','missing category query keeps the preset');$_GET['shootcal_testimonials_category']='';check($resolve->invoke(new Shortcode,'preset','on')==='','All reviews clears a preset category');$_GET['shootcal_testimonials_category']=['malformed'];check($resolve->invoke(new Shortcode,'preset','on')==='preset','malformed category query keeps the preset');unset($_GET['shootcal_testimonials_category']);
 $assets=new Assets; $assets->note_usage([get_post($p)],false);$assets->enqueue();check(wp_script_is('shootcal-testimonials','enqueued'),'dialog script loads without View more');
 $validate=new ReflectionMethod(Form::class,'validate');$spamForm=new Form;$validate->invoke($spamForm,'Example Reviewer','Unrelated promotional content https://example.test/spam', '',0,'');$errors=new ReflectionProperty(Form::class,'errors');check(isset($errors->getValue($spamForm)['quote']),'promotional web links rejected without creating a post');
 $compat=new ShootCalTestimonials\Compatibility;$compat->register();$flag=new ReflectionProperty(ShootCalTestimonials\Compatibility::class,'purge_pending');update_post_meta($p,'shootcal_testimonials_review_title','Changed title');check($flag->getValue($compat),'published metadata schedules cache refresh');$compat->flush_pending();check(!$flag->getValue($compat),'cache refresh flushes once');wp_delete_post($second,true);check($flag->getValue($compat),'published deletion schedules cache refresh');
 $target=new ReflectionMethod(Form::class,'redirect_target');$_POST[Form::FIELD_REDIRECT]='';$_REQUEST['_wp_http_referer']='/?page_id=67';$_SERVER['REQUEST_URI']='/?page_id=67';check(str_contains($target->invoke(new Form),'page_id=67'),'self-posted form retains confirmation page');$_POST[Form::FIELD_REDIRECT]='https://untrusted.example/';check(str_contains($target->invoke(new Form),'page_id=67'),'off-host redirect falls back to the submission page');$_REQUEST['_wp_http_referer']='https://untrusted.example/';check($target->invoke(new Form)===home_url('/'),'off-host referer cannot redirect visitors');
 check(post_type_supports('shootcal_testimonial','custom-fields'),'REST metadata editable through core');
 $credit_before=Config::get('show_form_credit',false);Config::set('show_form_credit',false);check(!str_contains((new Form)->render([]),'sct-form__credit'),'credit absent when disabled');check(defined('DONOTCACHEPAGE')&&DONOTCACHEPAGE,'rendered form protects its nonce from page caching');Config::set('show_form_credit',true);$credit_html=(new Form)->render([]);check(str_contains($credit_html,'sct-form__credit')&&str_contains($credit_html,'https://shootcal.com/'),'opt-in form credit links to ShootCal');Config::set('show_form_credit',$credit_before);check(Config::defaults()['show_form_credit']===false,'new installation credit is opt-in');
 $pattern=wp_insert_post(['post_type'=>'wp_block','post_status'=>'publish','post_title'=>'Regression Form Pattern','post_content'=>'[shootcal_testimonial_form]']);$made[]=$pattern;$form_content=new ReflectionMethod(Assets::class,'content_has_form');check($form_content->invoke(new Assets,'<!-- wp:block {"ref":'.$pattern.'} /-->'),'synced form pattern is detected before page-cache headers');
 $_GET[Form::OPEN_QUERY_VAR]='1';$inline_html=(new Form)->render(['mode'=>'dialog']);check((bool)preg_match('/<div class="sct-form-wrap" id="sct-form-[^"]+-dialog">/',$inline_html),'no-script form target exists on inline wrapper');unset($_GET[Form::OPEN_QUERY_VAR]);
 $token_method=new ReflectionMethod(Form::class,'honeypot_token');$verify_method=new ReflectionMethod(Form::class,'is_honeypot_token');$old_ip=$_SERVER['REMOTE_ADDR']??null;$_SERVER['REMOTE_ADDR']='192.0.2.14';$token=$token_method->invoke(new Form,time());$tampered=substr($token,0,-1).(substr($token,-1)==='0'?'1':'0');check(strlen($token)===Form::TOKEN_LENGTH&&$verify_method->invoke(new Form,$token),'stateless honeypot acknowledgement is valid for its source');check(!$verify_method->invoke(new Form,$token.'a')&&!$verify_method->invoke(new Form,$tampered),'tampered honeypot acknowledgement is rejected');check(!$verify_method->invoke(new Form,$token_method->invoke(new Form,time()-Form::NOTICE_TTL-1)),'expired honeypot acknowledgement is rejected');$_SERVER['REMOTE_ADDR']='192.0.2.15';check(!$verify_method->invoke(new Form,$token),'honeypot acknowledgement is bound to its source');if($old_ip===null){unset($_SERVER['REMOTE_ADDR']);}else{$_SERVER['REMOTE_ADDR']=$old_ip;}

 $icons=new ShootCalTestimonials\Category_Icons;$safe='<svg viewBox="0 0 24 24"><path d="M1 1L8 8" stroke="currentColor"/></svg>';
 check(str_contains($icons::sanitize_svg($safe),'aria-hidden="true"'),'static custom SVG stays decorative');
 foreach(['<svg><script>alert(1)</script></svg>','<svg><foreignObject><div>unsafe</div></foreignObject></svg>','<!DOCTYPE svg [<!ENTITY x SYSTEM "file:///etc/passwd">]><svg>&x;</svg>','<svg><image href="https://example.test/icon"/></svg>','<svg><path fill="url(https://example.test/a)"/></svg>','<svg><path fill="\\75rl(\\68ttp://example.test/a)"/></svg>'] as $bad){check($icons::sanitize_svg($bad)==='','unsafe SVG content rejected');}
 check(!str_contains($icons::sanitize_svg('<svg onload="alert(1)"><path d="M0 0"/></svg>'),'onload'),'SVG event handlers removed');
 $term=wp_insert_term('Regression Icon Category','shootcal_testimonials_category');$tid=$term['term_id'];wp_set_current_user($admin->ID);$_POST=['shootcal_testimonials_category_icon_nonce'=>wp_create_nonce('shootcal_testimonials_category_icon'),'shootcal_testimonials_icon'=>'custom','shootcal_testimonials_icon_svg'=>$safe];$icons->save($tid);check(str_contains($icons::icon($tid),'M1 1L8 8'),'category custom icon persists and renders');
 $_POST['shootcal_testimonials_icon_svg']='<svg><script/></svg>';$icons->save($tid);check(str_contains($icons::icon($tid),'M1 1L8 8'),'invalid custom icon preserves prior icon');
 $_POST['shootcal_testimonials_category_icon_nonce']='invalid';$_POST['shootcal_testimonials_icon']='ring';$icons->save($tid);check(get_term_meta($tid,'shootcal_testimonials_icon',true)==='custom','category icon rejects invalid nonce');
 $_POST['shootcal_testimonials_category_icon_nonce']=wp_create_nonce('shootcal_testimonials_category_icon');wp_set_current_user(0);$icons->save($tid);check(get_term_meta($tid,'shootcal_testimonials_icon',true)==='custom','anonymous cannot edit category icons');
 wp_set_current_user($admin->ID);$preset_ok=true;foreach($icons::presets() as $key=>$label){if(!$key||$key==='custom')continue;update_term_meta($tid,'shootcal_testimonials_icon',$key);$preset_ok=$preset_ok&&str_contains($icons::icon($tid),'<path');}check($preset_ok,'all bundled Font Awesome presets render safely');wp_delete_term($tid,'shootcal_testimonials_category');
 check(Config::valid_as_of_date('2026-10-02')&&!Config::valid_as_of_date('2026-02-30')&&!Config::valid_as_of_date('later')&&!Config::valid_as_of_date('2099-01-01')&&!Config::valid_as_of_date('0000-01-01'),'aggregate date requires a real past or present ISO calendar date');
 check(Config::defaults()['default_count']===21&&Shortcode::DEFAULT_TOTAL>=30,'new defaults allow 21 reviews and a full nine-review batch');

 wp_set_current_user($admin->ID);$editor=new Editor;$_POST=['shootcal_testimonials_details_nonce'=>wp_create_nonce('shootcal_testimonials_review_details'),'shootcal_testimonials_details'=>['shootcal_testimonials_source'=>'trustpilot','shootcal_testimonials_source_url'=>'https://www.trustpilot.com/reviews/example']];$editor->save($p);check(get_post_meta($p,'shootcal_testimonials_source',true)==='trustpilot'&&get_post_meta($p,'shootcal_testimonials_source_url',true)==='https://www.trustpilot.com/reviews/example','editor source selection and optional link persist');
 ob_start();$editor->render(get_post($p));$editor_html=ob_get_clean();check(str_contains($editor_html,'Originally posted on')&&str_contains($editor_html,'type="url"')&&substr_count($editor_html,'id="shootcal_testimonials_source"')===1,'source selector and URL input render once');
 $labels=Meta::source_labels();$all=true;foreach(Meta::SOURCES as $source){$all=$all&&isset($labels[$source])&&Meta::normalize_source($source)===$source&&str_contains($editor_html,'value="'.$source.'"');}check($all&&count($labels)===count(Meta::SOURCES),'every supported source appears in the editor and normalization');
 $source_html=(new Shortcode)->render(['count'=>'60']);check(str_contains($source_html,'Originally posted on Trustpilot')&&str_contains($source_html,'href="https://www.trustpilot.com/reviews/example"'),'source attribution displays readable platform and original link');
 $_POST['shootcal_testimonials_details']['shootcal_testimonials_source_url']='javascript:alert(1)';$editor->save($p);check(get_post_meta($p,'shootcal_testimonials_source_url',true)==='','unsafe source URL scheme rejected');
 $_POST['shootcal_testimonials_details_nonce']='invalid';$_POST['shootcal_testimonials_details']['shootcal_testimonials_source']='yelp';$editor->save($p);check(get_post_meta($p,'shootcal_testimonials_source',true)==='trustpilot','editor rejects a missing valid nonce');
 $_POST['shootcal_testimonials_details_nonce']=wp_create_nonce('shootcal_testimonials_review_details');wp_set_current_user(0);$editor->save($p);check(get_post_meta($p,'shootcal_testimonials_source',true)==='trustpilot','anonymous cannot alter review source');

}catch(Throwable $e){fwrite(STDERR,"FAIL ".$e->getMessage()."\n");exit(1);}finally{foreach($made as $id)wp_delete_post($id,true);$_POST=[];unset($_REQUEST['_wp_http_referer']);}
